import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import LineTabs from "./components/Tabs";
import { Toaster } from "@/components/ui/toaster"

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400","500","700"],
  variable:"--font-poppins",
  display:"swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar></Navbar>
        <LineTabs></LineTabs>
        {children}
        <Toaster />
        </body>
    </html>
  );
}
